### ISSUE TITLE
Prepopulate inputs

### ISSUE THREAD

**Issue by tobaco** [justonestep/processwire-simplecontactform#1]
Hey there! ;-)

Is there any possibility to prepopulate an input field/selectbox with data e.g. from an url query string?

thanks!

**Comment by justb3a** [comment]
Hey!

Imagine you have the following url: http://xxx.com/contact/?phone=foo
You can do something like this in simple_contact_form.php:

``` php
<?php 
if (empty($input->phone) && isset($input->get->phone)) {
  $input->phone = $sanitizer->text($input->get->phone);
}
?>
<input name="phone" value="<?= $input->phone; ?>" type="text" />
```

**Comment by tobaco** [comment]
öhm, that's the way i would do it, if i code the form by hand. but i thought your module would render the whole form with

``` php
$content = $modules->get('SimpleContactForm')->render(); //php
```

so, where would i add your code?

thanks!

**Comment by justb3a** [comment]
This module creates a simple template called _simple_contact_form.php_, you can / should change the html structure and add/change everything you want. 

``` php
$content = $modules->get('SimpleContactForm')->render();
```

places the created form/template in a specific template. Think of this template as a partial which will be included by calling `$modules->get('SimpleContactForm')->render();`.

It's really important for me that you're able to adapt any html to your own needs.

**Comment by tobaco** [comment]
Ah, ok. I thought you would use the standard processwire form helper.

Thanks!

**Comment by justb3a** [comment]
I use the standard processwire form helper to create the template (and the fields) ;)
