### ISSUE TITLE
the form works in the Processwire system, but does not send email

### ISSUE THREAD

**Issue by gytdev** [justonestep/processwire-simplecontactform#13]
Hello dear creator. 

Thank You for a good looking contact form. I have created a process-wire site and used it.

The contact form appears clearly on the contact page that customers see. If I fill up the contact form from the customer end, press send, get a confirmation message.

The message appears in admin panel under Pages>Contact from Messages.

But the problem is that i don't get the email in the email box that is provided in the admin panel under Modules>Site>SimpleContact>Form

Is this a bug, or did I miss something?

**Comment by justb3a** [comment]
Hey,

did you have a look at your logfiles?

- ProcessWire backend > logs > simplecontactform.log
- server mail logfile

If the mail doesn't get send, usually there is something wrong with the server mail setup.
Did you try to send a mail without using this module? Using php `mail()` function or via SSH from the command line?

**Comment by justb3a** [comment]
No feedback so far, I'm going to close this issue right now.  
Please feel free to reopen this if the problem still occurs.
