### ISSUE TITLE
Suggestion: Buttons for Messages on sfc-messages page

### ISSUE THREAD

**Issue by q2apro** [justonestep/processwire-simplecontactform#7]
Would be fantastic to have the "mark as spam" and "delete message" buttons on the `/scf-messages/` page. 

This way the user does not have to go into Tree>sfc_messages anymore and try to find the according one. 

Would be a big time saver.

**Comment by justb3a** [comment]
I thought about this from time to time but it would need a bit more logic than just adding these buttons. You need to wrap a `<form>` around all items containing an `<submit>` button. Then you need pagination for all items. All items on one page is definitely too much. Furthermore the latest version supporting ProcessWire 3.x changed a lot including the handling of the received messages. In the module settings you have to select a parent page. All entries created and managed will live under the parent you selected there. You could create a page "messages"; add a template which contains the form to mark messages as spam or delete them.
