### ISSUE TITLE
Hidden date field

### ISSUE THREAD

**Issue by binarious** [justonestep/processwire-simplecontactform#9]
I've just installed this module and rendered it without modifications. 
I noticed a label for the hidden `scf-date` field. Labels are not allowed to reference hidden fields via `for`. Besides that it doesn't make sense, too. Why this dead label and how can I remove it?

**Comment by justb3a** [comment]
Hi,
thanks for the hint. I didn't know that ProcessWire provides a way to skip the label. It's added to the develop branch, so it'll published with the next release!
